### ISSUE TITLE
Minimum Viable Product (MVP)

### ISSUE THREAD

**Issue by Tagaca19e** [Tagaca19e/verifai#4]
## TODO's for an MVP for the project
- [ ] Create a feature to parse entire essay or long text
- [x] Instant save for documents with results #8 
- [x] Document dashboard #10 
- [x] Document creating and deletion #12 #11  
- [x] Mark text that are flagged with high AI score
- [ ] Upload files either drag or drop or using a button
- [ ] Enable OCR for texts
- [x] Save file to a users account
- [x] Fix home page
